//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZED.IVMS7200.IVMS7200 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DevTreeInfoResult", Namespace="http://bean.server.ws.www.hikvision.com")]
    [System.SerializableAttribute()]
    public partial class DevTreeInfoResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZED.IVMS7200.IVMS7200.Area[] areaListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZED.IVMS7200.IVMS7200.DeviceNode[] deviceNodeListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> messageCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZED.IVMS7200.IVMS7200.Area[] areaList {
            get {
                return this.areaListField;
            }
            set {
                if ((object.ReferenceEquals(this.areaListField, value) != true)) {
                    this.areaListField = value;
                    this.RaisePropertyChanged("areaList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZED.IVMS7200.IVMS7200.DeviceNode[] deviceNodeList {
            get {
                return this.deviceNodeListField;
            }
            set {
                if ((object.ReferenceEquals(this.deviceNodeListField, value) != true)) {
                    this.deviceNodeListField = value;
                    this.RaisePropertyChanged("deviceNodeList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> messageCode {
            get {
                return this.messageCodeField;
            }
            set {
                if ((this.messageCodeField.Equals(value) != true)) {
                    this.messageCodeField = value;
                    this.RaisePropertyChanged("messageCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Area", Namespace="http://bean.server.ws.www.hikvision.com")]
    [System.SerializableAttribute()]
    public partial class Area : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int areaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string areaNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int parentAreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int areaId {
            get {
                return this.areaIdField;
            }
            set {
                if ((this.areaIdField.Equals(value) != true)) {
                    this.areaIdField = value;
                    this.RaisePropertyChanged("areaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string areaName {
            get {
                return this.areaNameField;
            }
            set {
                if ((object.ReferenceEquals(this.areaNameField, value) != true)) {
                    this.areaNameField = value;
                    this.RaisePropertyChanged("areaName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parentAreaId {
            get {
                return this.parentAreaIdField;
            }
            set {
                if ((this.parentAreaIdField.Equals(value) != true)) {
                    this.parentAreaIdField = value;
                    this.RaisePropertyChanged("parentAreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceNode", Namespace="http://bean.server.ws.www.hikvision.com")]
    [System.SerializableAttribute()]
    public partial class DeviceNode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alarmIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int alarmPortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZED.IVMS7200.IVMS7200.Channel[] channelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deviceaccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> deviceidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string devicenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> deviceuseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> haszerochannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> onlineStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int parentNodeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phonenumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ppvsIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ppvsPortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reservedStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rsmIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rsmPortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> serverrouteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> streamtypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int streamusertypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> transmitmodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alarmIp {
            get {
                return this.alarmIpField;
            }
            set {
                if ((object.ReferenceEquals(this.alarmIpField, value) != true)) {
                    this.alarmIpField = value;
                    this.RaisePropertyChanged("alarmIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int alarmPort {
            get {
                return this.alarmPortField;
            }
            set {
                if ((this.alarmPortField.Equals(value) != true)) {
                    this.alarmPortField = value;
                    this.RaisePropertyChanged("alarmPort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZED.IVMS7200.IVMS7200.Channel[] channels {
            get {
                return this.channelsField;
            }
            set {
                if ((object.ReferenceEquals(this.channelsField, value) != true)) {
                    this.channelsField = value;
                    this.RaisePropertyChanged("channels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deviceaccount {
            get {
                return this.deviceaccountField;
            }
            set {
                if ((object.ReferenceEquals(this.deviceaccountField, value) != true)) {
                    this.deviceaccountField = value;
                    this.RaisePropertyChanged("deviceaccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> deviceid {
            get {
                return this.deviceidField;
            }
            set {
                if ((this.deviceidField.Equals(value) != true)) {
                    this.deviceidField = value;
                    this.RaisePropertyChanged("deviceid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string devicename {
            get {
                return this.devicenameField;
            }
            set {
                if ((object.ReferenceEquals(this.devicenameField, value) != true)) {
                    this.devicenameField = value;
                    this.RaisePropertyChanged("devicename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> deviceuse {
            get {
                return this.deviceuseField;
            }
            set {
                if ((this.deviceuseField.Equals(value) != true)) {
                    this.deviceuseField = value;
                    this.RaisePropertyChanged("deviceuse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> haszerochannel {
            get {
                return this.haszerochannelField;
            }
            set {
                if ((this.haszerochannelField.Equals(value) != true)) {
                    this.haszerochannelField = value;
                    this.RaisePropertyChanged("haszerochannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> onlineStatus {
            get {
                return this.onlineStatusField;
            }
            set {
                if ((this.onlineStatusField.Equals(value) != true)) {
                    this.onlineStatusField = value;
                    this.RaisePropertyChanged("onlineStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parentNodeId {
            get {
                return this.parentNodeIdField;
            }
            set {
                if ((this.parentNodeIdField.Equals(value) != true)) {
                    this.parentNodeIdField = value;
                    this.RaisePropertyChanged("parentNodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phonenum {
            get {
                return this.phonenumField;
            }
            set {
                if ((object.ReferenceEquals(this.phonenumField, value) != true)) {
                    this.phonenumField = value;
                    this.RaisePropertyChanged("phonenum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ppvsIp {
            get {
                return this.ppvsIpField;
            }
            set {
                if ((object.ReferenceEquals(this.ppvsIpField, value) != true)) {
                    this.ppvsIpField = value;
                    this.RaisePropertyChanged("ppvsIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ppvsPort {
            get {
                return this.ppvsPortField;
            }
            set {
                if ((this.ppvsPortField.Equals(value) != true)) {
                    this.ppvsPortField = value;
                    this.RaisePropertyChanged("ppvsPort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reservedStr {
            get {
                return this.reservedStrField;
            }
            set {
                if ((object.ReferenceEquals(this.reservedStrField, value) != true)) {
                    this.reservedStrField = value;
                    this.RaisePropertyChanged("reservedStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rsmIp {
            get {
                return this.rsmIpField;
            }
            set {
                if ((object.ReferenceEquals(this.rsmIpField, value) != true)) {
                    this.rsmIpField = value;
                    this.RaisePropertyChanged("rsmIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rsmPort {
            get {
                return this.rsmPortField;
            }
            set {
                if ((this.rsmPortField.Equals(value) != true)) {
                    this.rsmPortField = value;
                    this.RaisePropertyChanged("rsmPort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> serverroute {
            get {
                return this.serverrouteField;
            }
            set {
                if ((this.serverrouteField.Equals(value) != true)) {
                    this.serverrouteField = value;
                    this.RaisePropertyChanged("serverroute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> streamtype {
            get {
                return this.streamtypeField;
            }
            set {
                if ((this.streamtypeField.Equals(value) != true)) {
                    this.streamtypeField = value;
                    this.RaisePropertyChanged("streamtype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int streamusertype {
            get {
                return this.streamusertypeField;
            }
            set {
                if ((this.streamusertypeField.Equals(value) != true)) {
                    this.streamusertypeField = value;
                    this.RaisePropertyChanged("streamusertype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> transmitmode {
            get {
                return this.transmitmodeField;
            }
            set {
                if ((this.transmitmodeField.Equals(value) != true)) {
                    this.transmitmodeField = value;
                    this.RaisePropertyChanged("transmitmode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Channel", Namespace="http://bean.server.ws.www.hikvision.com")]
    [System.SerializableAttribute()]
    public partial class Channel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string channelnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> channenumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channelname {
            get {
                return this.channelnameField;
            }
            set {
                if ((object.ReferenceEquals(this.channelnameField, value) != true)) {
                    this.channelnameField = value;
                    this.RaisePropertyChanged("channelname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> channenum {
            get {
                return this.channenumField;
            }
            set {
                if ((this.channenumField.Equals(value) != true)) {
                    this.channenumField = value;
                    this.RaisePropertyChanged("channenum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceGpsStatus", Namespace="http://bean.server.ws.www.hikvision.com")]
    [System.SerializableAttribute()]
    public partial class DeviceGpsStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deviceAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int deviceStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZED.IVMS7200.IVMS7200.GpsData gpsDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deviceAccount {
            get {
                return this.deviceAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.deviceAccountField, value) != true)) {
                    this.deviceAccountField = value;
                    this.RaisePropertyChanged("deviceAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int deviceStatus {
            get {
                return this.deviceStatusField;
            }
            set {
                if ((this.deviceStatusField.Equals(value) != true)) {
                    this.deviceStatusField = value;
                    this.RaisePropertyChanged("deviceStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZED.IVMS7200.IVMS7200.GpsData gpsData {
            get {
                return this.gpsDataField;
            }
            set {
                if ((object.ReferenceEquals(this.gpsDataField, value) != true)) {
                    this.gpsDataField = value;
                    this.RaisePropertyChanged("gpsData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GpsData", Namespace="http://bean.server.ws.www.hikvision.com")]
    [System.SerializableAttribute()]
    public partial class GpsData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string directionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string divisionEWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string divisionNSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string longitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiveTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string speedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direction {
            get {
                return this.directionField;
            }
            set {
                if ((object.ReferenceEquals(this.directionField, value) != true)) {
                    this.directionField = value;
                    this.RaisePropertyChanged("direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string divisionEW {
            get {
                return this.divisionEWField;
            }
            set {
                if ((object.ReferenceEquals(this.divisionEWField, value) != true)) {
                    this.divisionEWField = value;
                    this.RaisePropertyChanged("divisionEW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string divisionNS {
            get {
                return this.divisionNSField;
            }
            set {
                if ((object.ReferenceEquals(this.divisionNSField, value) != true)) {
                    this.divisionNSField = value;
                    this.RaisePropertyChanged("divisionNS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.latitudeField, value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.longitudeField, value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string receiveTime {
            get {
                return this.receiveTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.receiveTimeField, value) != true)) {
                    this.receiveTimeField = value;
                    this.RaisePropertyChanged("receiveTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string speed {
            get {
                return this.speedField;
            }
            set {
                if ((object.ReferenceEquals(this.speedField, value) != true)) {
                    this.speedField = value;
                    this.RaisePropertyChanged("speed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server.ws.www.hikvision.com/", ConfigurationName="IVMS7200.IGetDevTreeService")]
    public interface IGetDevTreeService {
        
        // CODEGEN: 命名空间  的元素名称 getDevTreeInfoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ZED.IVMS7200.IVMS7200.getDevTreeInfoResponse getDevTreeInfo(ZED.IVMS7200.IVMS7200.getDevTreeInfo request);
        
        // CODEGEN: 命名空间  的元素名称 getDeviceGpsStatusResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ZED.IVMS7200.IVMS7200.getDevGpsStatusResponse getDevGpsStatus(ZED.IVMS7200.IVMS7200.getDevGpsStatus request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDevTreeInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDevTreeInfo", Namespace="http://server.ws.www.hikvision.com/", Order=0)]
        public ZED.IVMS7200.IVMS7200.getDevTreeInfoBody Body;
        
        public getDevTreeInfo() {
        }
        
        public getDevTreeInfo(ZED.IVMS7200.IVMS7200.getDevTreeInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDevTreeInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int route;
        
        public getDevTreeInfoBody() {
        }
        
        public getDevTreeInfoBody(string username, string password, int route) {
            this.username = username;
            this.password = password;
            this.route = route;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDevTreeInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDevTreeInfoResponse", Namespace="http://server.ws.www.hikvision.com/", Order=0)]
        public ZED.IVMS7200.IVMS7200.getDevTreeInfoResponseBody Body;
        
        public getDevTreeInfoResponse() {
        }
        
        public getDevTreeInfoResponse(ZED.IVMS7200.IVMS7200.getDevTreeInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDevTreeInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZED.IVMS7200.IVMS7200.DevTreeInfoResult getDevTreeInfoResult;
        
        public getDevTreeInfoResponseBody() {
        }
        
        public getDevTreeInfoResponseBody(ZED.IVMS7200.IVMS7200.DevTreeInfoResult getDevTreeInfoResult) {
            this.getDevTreeInfoResult = getDevTreeInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDevGpsStatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDevGpsStatus", Namespace="http://server.ws.www.hikvision.com/", Order=0)]
        public ZED.IVMS7200.IVMS7200.getDevGpsStatusBody Body;
        
        public getDevGpsStatus() {
        }
        
        public getDevGpsStatus(ZED.IVMS7200.IVMS7200.getDevGpsStatusBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDevGpsStatusBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string deviceAccount;
        
        public getDevGpsStatusBody() {
        }
        
        public getDevGpsStatusBody(string deviceAccount) {
            this.deviceAccount = deviceAccount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDevGpsStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDevGpsStatusResponse", Namespace="http://server.ws.www.hikvision.com/", Order=0)]
        public ZED.IVMS7200.IVMS7200.getDevGpsStatusResponseBody Body;
        
        public getDevGpsStatusResponse() {
        }
        
        public getDevGpsStatusResponse(ZED.IVMS7200.IVMS7200.getDevGpsStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDevGpsStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZED.IVMS7200.IVMS7200.DeviceGpsStatus getDeviceGpsStatusResult;
        
        public getDevGpsStatusResponseBody() {
        }
        
        public getDevGpsStatusResponseBody(ZED.IVMS7200.IVMS7200.DeviceGpsStatus getDeviceGpsStatusResult) {
            this.getDeviceGpsStatusResult = getDeviceGpsStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDevTreeServiceChannel : ZED.IVMS7200.IVMS7200.IGetDevTreeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDevTreeServiceClient : System.ServiceModel.ClientBase<ZED.IVMS7200.IVMS7200.IGetDevTreeService>, ZED.IVMS7200.IVMS7200.IGetDevTreeService {
        
        public GetDevTreeServiceClient() {
        }
        
        public GetDevTreeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDevTreeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDevTreeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDevTreeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZED.IVMS7200.IVMS7200.getDevTreeInfoResponse ZED.IVMS7200.IVMS7200.IGetDevTreeService.getDevTreeInfo(ZED.IVMS7200.IVMS7200.getDevTreeInfo request) {
            return base.Channel.getDevTreeInfo(request);
        }
        
        public ZED.IVMS7200.IVMS7200.DevTreeInfoResult getDevTreeInfo(string username, string password, int route) {
            ZED.IVMS7200.IVMS7200.getDevTreeInfo inValue = new ZED.IVMS7200.IVMS7200.getDevTreeInfo();
            inValue.Body = new ZED.IVMS7200.IVMS7200.getDevTreeInfoBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.route = route;
            ZED.IVMS7200.IVMS7200.getDevTreeInfoResponse retVal = ((ZED.IVMS7200.IVMS7200.IGetDevTreeService)(this)).getDevTreeInfo(inValue);
            return retVal.Body.getDevTreeInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZED.IVMS7200.IVMS7200.getDevGpsStatusResponse ZED.IVMS7200.IVMS7200.IGetDevTreeService.getDevGpsStatus(ZED.IVMS7200.IVMS7200.getDevGpsStatus request) {
            return base.Channel.getDevGpsStatus(request);
        }
        
        public ZED.IVMS7200.IVMS7200.DeviceGpsStatus getDevGpsStatus(string deviceAccount) {
            ZED.IVMS7200.IVMS7200.getDevGpsStatus inValue = new ZED.IVMS7200.IVMS7200.getDevGpsStatus();
            inValue.Body = new ZED.IVMS7200.IVMS7200.getDevGpsStatusBody();
            inValue.Body.deviceAccount = deviceAccount;
            ZED.IVMS7200.IVMS7200.getDevGpsStatusResponse retVal = ((ZED.IVMS7200.IVMS7200.IGetDevTreeService)(this)).getDevGpsStatus(inValue);
            return retVal.Body.getDeviceGpsStatusResult;
        }
    }
}
